server:
  port: 8081
spring:
  application:
    name: pvs
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 100s
  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  type-aliases-package: com.pvs.entity
logging:
  level:
    com.hmdp: debug
